### ISSUE TITLE
[功能请求] 通过直接程序参数的形式直接导入种子降低延迟并提高性能

### ISSUE THREAD

**Issue by lhllhx** [qfishpear/fishrss#1]
irssi下载种子后可以直接执行程序  deluge 也可以通过deluge-console直接导入种子 两者结合应该能有效提高性能

**Comment by lhllhx** [comment]
irssi也是自带文件过滤的 建议把fl token模块独立出来 需要时直接调用即可 降低延迟

**Comment by qfishpear** [comment]
关于降低延迟：
嗯我有想过这个，但这个需求真的重要吗，那些要r光速种的人本来就不需要过滤吧。。。只要带ban人就必须请求api至少有0.1s延迟，我觉得0.1s和0.3s区别真不大，都足够被光速种干死了。而且绑定到deluge会降低对小白的友好程度，毕竟原本的设计里面r种过滤部分是不绑定任何bt客户端的。
关于fl token：
这个可以实现，我会加一个独立的脚本。

**Comment by lhllhx** [comment]
个人并不觉得有完全的小白去刷红 红现在100%都是lw在刷 基本没有官方正常的qb和rt，而会修改文件编译的可以说完全不叫小白了。而且这两个同时保留不冲突 留个开关是否启用监控目录就行了 

关于fl token独立脚本：
个人思路 irssi或脚本->调用脚本->脚本直接下载fl->脚本调用de（可能这些用sh脚本就能将延迟降到最低）

**Comment by qfishpear** [comment]
1. 你有测试过deluge监控文件夹和直接调用deluge命令之间的延迟差异吗？
2. 假设这个延迟差异为L，如果要调用api来ban人，那么将直接调用deluge命令的延迟当做0来看，网站api带来的延迟至少0.1s，那么L和这个0.1s在一个数量级上吗？0.1和0.1+L的延迟差异会影响到刷流吗？0.1和0.3呢？
3. 如果不调用api的话就不能ban人，那么除了使用fl token以外还有其他有必要用到此脚本的需求吗？

fl token的低延迟版本我会去实现，其他需求请描述清楚使用场景并给出足够的数据支持，不是所有的优化都是有意义的，如果真的追求极致低延迟你应该直接魔改autodl插件而不是用我的脚本。

而且小白和小白是不一样的，第一个吃我这个螃蟹的人就是个懂命令行操作的人，但是他就是完全不懂python。除非有显著效果提升不然我不想丧失脚本的泛用性。

**Comment by qfishpear** [comment]
fl token低延迟已实现

**Comment by qfishpear** [comment]
想了想发现下载链接里包含了种子id，这意味着可以并行下载种子和调用api，因此也许延迟不再是问题，这个功能变得可以实现了

**Comment by qfishpear** [comment]
并行调用api/下载种子，已实现
deluge推送，已实现

**Comment by lhllhx** [comment]
使用$(TorrentPathName) 从irssi导入种子可避免多次下载

**Comment by qfishpear** [comment]
> 使用$(TorrentPathName) 从irssi导入种子可避免多次下载

嗯后来我意识到我犯蠢了，后来的更新的filter.py已经提供这个功能了
