### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by huasheng666** [qfishpear/fishrss#4]
python3 check_config.py
运行正常，登录获取了站点用户信息
但最后一步辅种报错：
python3 reseed.py --site dic --dir /fishrss/red --result-dir /fishrss/red/QBresults
volume1/docker/fishrss/dic
  File "reseed.py", line 208
    torrent: collections.OrderedDict = bencode.decode(f.read())
           ^
SyntaxError: invalid syntax

**Comment by qfishpear** [comment]
检查一下是不是python3版本太老了？3.5以后的版本应该都支持type hint了

**Comment by huasheng666** [comment]
感谢，原来是3.5.1，升级到3.10可以运行了....
谢谢~
